Ran shfmt

diff --git a/build-ctx/config-release-info b/build-ctx/config-release-info
--- a/build-ctx/config-release-info
+++ b/build-ctx/config-release-info
@@ -20,8 +20,8 @@ echo "Applying custom os-release modifications to $OS_RELEASE_FILE..."
 # This assumes VERSION_ID is a simple number like 42
 BASE_FEDORA_VERSION_ID=$(grep '^VERSION_ID=' "$OS_RELEASE_FILE" | head -n 1 | cut -d'=' -f2 | tr -d '"')
 if [[ -z "$BASE_FEDORA_VERSION_ID" ]]; then
-    echo "ERROR: Could not find VERSION_ID in $OS_RELEASE_FILE. Cannot proceed." >&2
-    exit 1
+	echo "ERROR: Could not find VERSION_ID in $OS_RELEASE_FILE. Cannot proceed." >&2
+	exit 1
 fi
 
 NEW_VERSION="${BASE_FEDORA_VERSION_ID}.${CURRENT_DATE} (${REMIX_NAME})"
@@ -32,15 +32,15 @@ sed -i "s|^DOCUMENTATION_URL=.*|DOCUMENTATION_URL=\"https://github.com/${GITHUB_
 sed -i "s|^BUG_REPORT_URL=.*|BUG_REPORT_URL=\"https://github.com/${GITHUB_REPO_OWNER}/${GITHUB_REPO_NAME}/issues\"|" "$OS_RELEASE_FILE"
 
 if grep -q '^VARIANT=' "$OS_RELEASE_FILE"; then
-    sed -i "s|^VARIANT=.*|VARIANT=\"${REMIX_NAME}\"|" "$OS_RELEASE_FILE"
+	sed -i "s|^VARIANT=.*|VARIANT=\"${REMIX_NAME}\"|" "$OS_RELEASE_FILE"
 else
-    echo "VARIANT=\"${REMIX_NAME}\"" >> "$OS_RELEASE_FILE"
+	echo "VARIANT=\"${REMIX_NAME}\"" >>"$OS_RELEASE_FILE"
 fi
 
 if grep -q '^VARIANT_ID=' "$OS_RELEASE_FILE"; then
-    sed -i "s|^VARIANT_ID=.*|VARIANT_ID=${REMIX_NAME,,}|" "$OS_RELEASE_FILE"
+	sed -i "s|^VARIANT_ID=.*|VARIANT_ID=${REMIX_NAME,,}|" "$OS_RELEASE_FILE"
 else
-    echo "VARIANT_ID=${REMIX_NAME,,}" >> "$OS_RELEASE_FILE"
+	echo "VARIANT_ID=${REMIX_NAME,,}" >>"$OS_RELEASE_FILE"
 fi
 
 sed -i "s|^OSTREE_VERSION=.*|OSTREE_VERSION='${NEW_OSTREE_VERSION}'|" "$OS_RELEASE_FILE"
